Race condition in RunCmdWithOutputParser
jfrog/gofrog pull request #41
Opened 2023-11-28 14:36 UTC by eranturgeman

- [x] All [tests](https://github.com/jfrog/gofrog#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
- [x] I labeled this pull request with one of the following: 'breaking change', 'new feature', 'bug', or 'ignore for release'

---

2023-11-28 15:27 UTC, yahavi requested changes

2023-11-28 15:27 UTC, yahavi commented on io/cmd.go
> +						Line:           line,
```suggestion
						RegExp:         regExp.RegExp,
						MatchedResults: regExp.RegExp.FindStringSubmatch(line),
						Line:           line,
						ExecFunc:       regExp.ExecFunc,
```

Even better if you could export this logic to a new function and reuse it

2023-11-28 15:27 UTC, yahavi commented on io/cmd.go
> +						Line:           line,
```suggestion
						RegExp:         regExp.RegExp,
						MatchedResults: regExp.RegExp.FindStringSubmatch(line),
						Line:           line,
						ExecFunc:       regExp.ExecFunc,
```

2023-11-29 12:31 UTC, yahavi commented
* Fix race condition in RunCmdWithOutputParser
* Update Go to 1.20
* Move `Command` struct from build-info-go

Dependency for https://github.com/jfrog/build-info-go/pull/216 & https://github.com/jfrog/jfrog-cli-core/pull/1053

2023-11-30 08:15 UTC, attiasas reviewed
Nice! please consider my comments

2023-11-30 08:15 UTC, attiasas commented on io/cmd.go
> +	}
```suggestion
		if !regExp.RegExp.MatchString(processedLine) {
			continue
		}
		results := CmdOutputPattern{
			RegExp:         regExp.RegExp,
			MatchedResults: regExp.RegExp.FindStringSubmatch(processedLine),
			Line:           processedLine,
			ExecFunc:       regExp.ExecFunc,
		}
		if processedLine, err = regExp.ExecFunc(&results); err != nil {
			errChan <- err
			hasError = true
			break
		}
	}
```

2023-11-30 08:15 UTC, attiasas commented on io/cmd_test.go
> +	assert.NoError(t, err)
```suggestion
	parserCalled := false
	stdout, stderr, exitOk, err := RunCmdWithOutputParser(config, false, &CmdOutputPattern{
		RegExp:   matchAllRegexp,
		ExecFunc: func(pattern *CmdOutputPattern) (string, error) {
			parserCalled = true
			return pattern.Line, nil 
		},
	})
	assert.NoError(t, err)
	assert.True(t, parserCalled)
```
lets also make sure the parser is also called at this process

2023-11-30 08:15 UTC, attiasas commented on io/cmd_test.go
> +		t.Run("", func(t *testing.T) {
lets add names to the tests to have clear logs for them and not:
```
--- PASS: TestRunCmdWithOutputParserError (0.00s)
=== RUN   TestProcessLine
=== RUN   TestProcessLine/#00
=== RUN   TestProcessLine/#01
=== RUN   TestProcessLine/#02
=== RUN   TestProcessLine/#03
=== RUN   TestProcessLine/#04
=== RUN   TestProcessLine/#05
--- PASS: TestProcessLine (0.00s)
    --- PASS: TestProcessLine/#00 (0.00s)
    --- PASS: TestProcessLine/#01 (0.00s)
    --- PASS: TestProcessLine/#02 (0.00s)
    --- PASS: TestProcessLine/#03 (0.00s)
    --- PASS: TestProcessLine/#04 (0.00s)
    --- PASS: TestProcessLine/#05 (0.00s)
```

2023-11-30 09:17 UTC, merged